### PR TITLE
Direction ability

### PR DESCRIPTION
**Pull request by ofirelarat**
Added the ability to choose the steps nav direction (rows or columns)

image

```
<MultiStep   
    steps: {[
       { component: <StepOne /> },
       {  component: <StepTwo /> },
       {  component: <StepThree /> },
       {  component: <StepFour /> }
    ]},
    activeStep: 0,
    direction: 'column' />
```

image

and not interfered the regular direction
image

image

### CODE REVIEW

**Comment by srdjan** [comment]
it seems from the screenshots (will try it locally tomorrow) that checkmarks don't rotate when orientation is vertical?

**Comment by srdjan** [comment]
@ofirelarat please rebase - I had some time and started to work/prepare for #80 & #98

**Comment by srdjan** [comment]
@ofirelarat please rebase - I had some time and started to work/prepare for #80 & #98

**Comment by ofirelarat** [comment]
@srdjan I rebased the branch

**Comment by ofirelarat** [comment]
But now it look like the Codeball test failed

**Comment by srdjan** [comment]
Ok, I disabled Codeball for now... New tool, don't need extra checks :)
please try again

**Comment by ofirelarat** [comment]
How can I run it again now?

**Comment by srdjan** [comment]
you can just push a small commit (in the future, I just did it for this PR) and it will rerun...

**Comment by srdjan** [comment]
please don't delete this branch after merging to main, I've started a major refactor that will result in a new major release and at that time we will need to re-apply this PR. I'm changing how the component is styled, in a such way that it is more aligned  with goober css library. It will allow for a lot easier adding of features going forward. That will bring major version bump to 6.x.x since it will contain breaking changes

**Comment by srdjan** [comment]
@ofirelarat can you please test/check https://github.com/srdjan/react-multistep/tree/story-98?
this implements more extensive external styling... It will be new major version, it is not backwards compatible with 5.x 
it would be nice to try merge this PR, too.

**Comment by ofirelarat** [comment]
I will check it

**Pull request merged**
