### PR TITLE
Add steps titles

### PR DESCRIPTION
**Pull request by ofirelarat**
PR of adding the steps title,
[related issue](https://github.com/srdjan/react-multistep/issues/81)

I tested it on mobile and tablet view as well and its look fine as the title with the index only looked like

you can see some scenarios below, or checkout to the branch and test it yourself
wide view:
image
narrow view no titles:
image
narrow view with titles:
image

### CODE REVIEW

**Comment by srdjan** [comment]
awesome!
Can you resolve conflicts against main? 

"This branch cannot be rebased due to conflicts"

**Comment by ofirelarat** [comment]
Its shows me that there are no conflicts with the base branch, are you sure?

**Comment by srdjan** [comment]
Screen Shot 2022-10-21 at 8 06 53 AM

I can't even see what are these conflicts, very weird. 
I added you as collaborator - welcome to the team :) 
Try to merge it yourself?

**Comment by ofirelarat** [comment]
Thanks!

**Pull request merged**
