### PR TITLE
refactor code to jsx and es6

### PR DESCRIPTION
**Pull request by kaadash**
Hi!
According to #14 I tried to port component to ES6. I used jsx syntax and I saw your commit where you remove it. 
Thanks for great component!

### CODE REVIEW

**Comment by Srdjan** [comment]
Hi @kaadash can you explain why do you need component implementation to be with JSX, it shouldn't matter in your application code?

**Comment by kaadash** [comment]
Thank you for quick response. I wanted to use jsx because it was easier to understand code when there is no decumentation. What is more adding new features will be easier. I can change this PR to be jsx independent. Could you tell me is it good way I refactor this component to ES6?

**Comment by Srdjan** [comment]
like your code - will take a look over the weekend... I would like to keep this component available to people that don't use JSX, too... Interesting problem.

**Comment by Srdjan** [comment]
@kaadash thanks!

**Comment by kaadash** [comment]
You're welcome. I've created new PR already #16 :) When you have time, please look at this new one. Have a nice day!

**Comment by kabala** [comment]
How do I import this amazing great component using ES6?

**Comment by srdjan** [comment]
@kabala current example does use ES6 import... take a look here: https://github.com/srdjan/react-multistep/blob/master/example/app/app.js

**Pull request merged**
